### ISSUE TITLE
如何清除所有缓存

### ISSUE THREAD

**Issue by HelloWorld-L** [FussenYu/AppCache#9]
DiskLruCache 有个 delete 方法来清除所有缓存，在这个库里面有什么办法能删除所有缓存嘛？ 目前只有把所有的key放在一个集合里面 然后要删除所有的时候整个遍历一边remove

**Comment by FussenYu** [comment]
你的 缓存文件夹的路径你是知道的，写个方法直接删除这个路径下的文件夹里面的所有东西 


​
 		
余福升
深圳乐道信息科技有限公司
18219200511 | fusheng.yu@banmabao.net
深圳市龙岗区坂田街道大光勘村五和商业街5-13号2楼205
